=== giso360/observer-pattern/store.xsd
<?xml version="1.0" encoding="utf-8"?>
<!-- Created with Liquid Technologies Online Tools 1.0 (https://www.liquid-technologies.com) -->
<xs:schema xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" attributeFormDefault="unqualified" elementFormDefault="qualified" xmlns:xs="http://www.w3.org/2001/XMLSchema">
  <xs:element name="store">
    <xs:complexType>
      <xs:sequence>
        <xs:element minOccurs="0" name="products">
          <xs:complexType>
            <xs:sequence>
              <xs:element minOccurs="0" maxOccurs="unbounded" name="product">
                <xs:complexType>
                  <xs:sequence>
                    <xs:element minOccurs="0" name="productName" type="xs:string" />
                    <xs:element minOccurs="0" name="price" type="xs:unsignedByte" />
                    <xs:element minOccurs="0" name="stockVolume" type="xs:unsignedShort" />
                  </xs:sequence>
                  <xs:attribute name="productid" type="xs:unsignedByte" use="optional" />
                </xs:complexType>
              </xs:element>
            </xs:sequence>
          </xs:complexType>
        </xs:element>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
</xs:schema>

=== giso360/observer-pattern/store.xml
<?xml version="1.0" encoding="UTF-8" ?>
<store xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="store.xsd">
    <products>
        <product productid="001">
            <productName>KINGSTON USB</productName>
            <price>10</price>
            <stockVolume>1000</stockVolume>
        </product>
        <product productid="002">
            <productName>XP USB</productName>
            <price>7</price>
            <stockVolume>2000</stockVolume>
        </product>
        <product productid="003">
            <productName>AMD USB</productName>
            <price>17</price>
            <stockVolume>500</stockVolume>
        </product>
    </products>
</store>
